name: flutter_boring_avatars
description: Boring avatars can generate unique avatars based on the username and color palette.
version: 2.1.0
homepage: https://github.com/xioxin/flutter_boring_avatars
repository: https://github.com/xioxin/flutter_boring_avatars
issue_tracker: https://github.com/xioxin/flutter_boring_avatars/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

funding:
  - https://ko-fi.com/xioxin

topics:
  - ui
  - avatar
  - widget
  - design
  - animation

screenshots:
  - description: An avatar example
    path: screenshots/logo.png
  - description: Examples of different types of avatars
    path: screenshots/preview2.png
