name: flutter_boring_avatars
description: Flutter implementation of boring avatars that generates custom, round avatars from any username and color palette.
version: 1.0.0
homepage: https://github.com/xioxin/flutter_boring_avatars

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  svg_path_parser: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
